# 1. DB \uC124\uC815
# spring.datasource.url=jdbc:mysql://localhost:3306/safepill
# spring.datasource.username=root
# spring.datasource.password=DB_\uBE44\uBC00\uBC88\uD638_\uC785\uB825
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.properties.hibernate.show_sql=true
# spring.jpa.properties.hibernate.format_sql=true
# spring.jpa.properties.hibernate.use_sql_comments=true

# 2. \uACF5\uACF5\uB370\uC774\uD130 API \uC124\uC815
# open-api.data-go-kr.base-url=http://apis.data.go.kr
# open-api.data-go-kr.service-key=\uBC1C\uAE09\uBC1B\uC740_\uB514\uCF54\uB529\uD0A4_\uC785\uB825
# open-api.data-go-kr.endpoint.medicine-identify=/1471000/MdcinGrnIdntfcInfoService03/getMdcinGrnIdntfcInfoList03
# open-api.data-go-kr.endpoint.medicine-ingredient=/1471000/DrugPrdtPrmsnInfoService07/getDrugPrdtMcpnDtlInq07
# open-api.data-go-kr.endpoint.medicine-precaution=/1471000/DrugPrdtPrmsnInfoService07/getDrugPrdtPrmsnDtlInq06

# 3. \uC2DD\uD488\uC548\uC804\uB098\uB77C (\uAC74\uAC15\uAE30\uB2A5\uC2DD\uD488) API \uC124\uC815
# open-api.food-safety.base-url=http://openapi.foodsafetykorea.go.kr/api
# open-api.food-safety.key=\uBC1C\uAE09\uBC1B\uC740_\uC778\uC99D\uD0A4_\uC785\uB825
# open-api.food-safety.service-id=C003
# open-api.food-safety.limit-service-id=I2710

# OpenAI API \uC784\uC2DC \uD0A4
# spring.ai.openai.api-key=sk-dummy-key-for-local-test