spring.application.name=safepill_be

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/safepill}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:change_me}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show_sql=${JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

open-api.data-go-kr.base-url=${DATA_GO_KR_BASE_URL:http://apis.data.go.kr}
open-api.data-go-kr.service-key=${DATA_GO_KR_SERVICE_KEY:change_me}
open-api.data-go-kr.endpoint.medicine-identify=/1471000/MdcinGrnIdntfcInfoService03/getMdcinGrnIdntfcInfoList03
open-api.data-go-kr.endpoint.medicine-ingredient=/1471000/DrugPrdtPrmsnInfoService07/getDrugPrdtMcpnDtlInq07
open-api.data-go-kr.endpoint.medicine-precaution=/1471000/DrugPrdtPrmsnInfoService07/getDrugPrdtPrmsnDtlInq06
open-api.data-go-kr.endpoint.dur-taboo=/1471000/DURIrdntInfoService03/getUsjntTabooInfoList02
open-api.data-go-kr.endpoint.druginfo=/1471000/DrbEasyDrugInfoService//getDrbEasyDrugList

open-api.food-safety.base-url=${FOOD_SAFETY_BASE_URL:http://openapi.foodsafetykorea.go.kr/api}
open-api.food-safety.key=${FOOD_SAFETY_KEY:change_me}
open-api.food-safety.service-id=${FOOD_SAFETY_SERVICE_ID:C003}
open-api.food-safety.limit-service-id=${FOOD_SAFETY_LIMIT_SERVICE_ID:I2710}

spring.ai.openai.api-key=${OPENAI_API_KEY:change_me}

gemini.api.key=${GEMINI_API_KEY:change_me}
gemini.api.url=${GEMINI_API_URL:https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent}

jwt.secret=${JWT_SECRET:change_me_change_me_change_me_change_me}
jwt.expiration=${JWT_EXPIRATION:3600000}
